Category, group and subgroup support
4d49/object-inspector pull request #4
Opened 2024-04-15 22:04 UTC by NullMember

Basic category, group and subgroup support. Group and subgroup automatically hides nodes under them.

2024-04-16 04:23 UTC, 4d49 commented
I found the problem. If you collapse/expand a group, subgroups will be expanded, but the button state will not be pressed and will need to be pressed twice.

2024-04-16 12:21 UTC, NullMember commented
Last commit should fix the issue

2024-04-17 04:17 UTC, 4d49 commented
The `test_1` property is always hidden in the inspector .

```gdscript
@export_category("Сategory")

@export_group("The property is always hidden")
@export var test_1: bool = true

@export_subgroup("In a subgroup, everything works")
@export var test_2: bool = true
```

2024-04-17 04:21 UTC, 4d49 commented
A radical solution to the problem would be to add properties as child nodes to categories/groups. But then there is the problem of finding properties.

2024-04-17 10:31 UTC, 4d49 requested changes

2024-04-17 10:31 UTC, 4d49 commented on scripts/inspector.gd
> +		if property["name"].ends_with(".gd"):
```suggestion
		elif property["name"].ends_with(".gd"):
```
To exclude the check if we've already started.

2024-04-17 11:18 UTC, merged