Added a new signal property_changed. Sent when a value is changed in the object inspector
4d49/object-inspector pull request #5
Opened 2024-04-16 02:01 UTC by angedelamort

This feature is really useful when you want to do certain updates based on a value changed.

2024-04-16 04:27 UTC, 4d49 commented
I'm sorry I don't understand exactly what this is for. Can you explain more? Or give me an example.

2024-04-16 22:00 UTC, angedelamort commented
Sure!

When you edit a property value in the inspector, it triggers a "OnPropertyChange" signal.

For example, in my case, I wanted to call queue_redraw() only when a certain value was changing. I have some custom "Draw" overrides and I don't want to call it every frame, so by registering a signal to the object_inspector, I'm notified when someone changes the value. I can then call the redraw.

2024-04-16 22:01 UTC, angedelamort commented
Also, an improvement that could be made is to send the previous and current value as parameter.

2024-04-17 04:27 UTC, 4d49 commented
If we're talking about a class object, why not use a setter for that?

```gdscript
@export var some_value: int = 0:
	set = set_some_value

func set_some_value(new_value: int) -> void:
	if some_value == new_value:
		return

	some_value = new_value

	if some_value == 42:
		queue_redraw()
```

2024-04-17 04:28 UTC, 4d49 commented
Or are you using this for a custom object of class `InspectorProperty`?

2024-04-17 22:58 UTC, angedelamort commented
Ok, I'll try again to explain again :)

- The object-inspector can handle any type of objects.
- When you set the object, it loads all the properties and their values (when you run the editor)
- (in running) when you change a value of a property, it sends a signal that a value of the object changed. You don't do "set_value", it's done by your inspector via reflectivity.
- When the signal is received, you can do something with it and you don't need to add code in your objects to handle this kind of use case.

You already have a signal for when you set an object, which is cool. Now I've added another signal for when a value has changed on that object. So you don't need to add code for each setter to set some kind of "global" variable that your object has changed. With that, it can handle everything, even objects that you don't necessarily have control on it. Or event adding more code/logic on game objects. In my use case, the main screen has the object inspector. There are different object types on the screen. So, when I receive a signal, I call the queueRefresh only on the currently selected object. And for all my object types, I don't need to add the snippet you have provided. And if I want to do something else later on, I just need to do it at one place.

I come from C# where the property grid was really useful when developing UI.  Here's the same event defined here:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.propertygrid.propertyvaluechanged?view=windowsdesktop-8.0

Hope this help?

2024-04-18 05:19 UTC, 4d49 requested changes

2024-04-18 05:21 UTC, 4d49 commented
Can you attach a minimal demo project? I am currently working on version `2.0` and need to look into your suggestion in more detail.

2024-04-18 14:03 UTC, smenardstingray commented
I'll try to have something ready soon.

2024-04-18 14:05 UTC, smenardstingray approved these changes

2026-03-20 04:43 UTC, closed without merging